/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./node_modules/flowbite-react/**/*.js",
    "./node_modules/rizzui/dist/*.{js,ts,jsx,tsx}", // ⚠️ Required this line to compile RizzUI style.
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: "#5A67D8",
        mainBlack: "#000000",
        mainGrey: "#FAFAFA",
        mainWhite: "#FFFFFF",
        lightBlue: "#EDF4FE",
        darkestBlue: "#12152E",
        darkBlue: "#2B305E",
      },
      backgroundImage: {
        herobg: "url('/images/herobg.png')",
        vectorone: "url('/images/subsidiaryvector.png')",
        shade: "url('/images/shade.png')",
        hero: "url('/images/cover.jpeg')",
        aboutus: "url('/images/aboutus.png')",
        arrowvector: "url('/images/vector.png')",
        arrowvector1: "url('/images/vector1.png')",
        arrowvector2: "url('/images/vector2.png')",
        edtech1: "url('/images/edtech1.svg')",
        edtechbg: "url('/images/edtechbg.svg')",
        edtechHero: "url('/images/edtechHero.svg')",
        retailBg: "url('/images/retailBg.svg')",
        retailBg2: "url('/images/retailBg2.svg')",
        features1: "url('/images/featuresbg/features1.png')",
        features2: "url('/images/featuresbg/features2.png')",
        features3: "url('/images/featuresbg/features3.png')",
        features4: "url('/images/featuresbg/features4.png')",
        features5: "url('/images/featuresbg/features5.png')",
        features6: "url('/images/featuresbg/features6.svg')",
        features7: "url('/images/featuresbg/features7.svg')",
        features8: "url('/images/featuresbg/features8.svg')",
        features9: "url('/images/featuresbg/features9.svg')",
        features10: "url('/images/featuresbg/features10.svg')",
        getHelpbg1: "url('/images/getHelpbg1.png')",
        getHelpbg2: "url('/images/getHelpbg2.png')",
        getHelpbg3: "url('/images/getHelpbg3.png')",
        getHelpbg4: "url('/images/getHelpbg4.png')",
        getHelpbg5: "url('/images/getHelpbg5.png')",
        getHelpbg6: "url('/images/getHelpbg6.png')",
        consultingHerobg: "url('/images/consultingHerobg.png')",
        homeHerobg1: "url('/images/HomeHerobg1.png')",
        homeHerobg2: "url('/images/HomeHerobg2.svg')",
        homeHerobg3: "url('/images/HomeHerobg3.png')",
        quote: "url('/images/quote.png')",
        Industrybg: "url('/images/Industrybg.png')",
        featuresbg: "url('/images/featuresbg.png')",
        featuresbg2: "url('/images/featuresbg2.png')",
        productbg: "url('/images/productbg.png')",
        vector4: "url('/images/vector4.png')",
        line: "url('/images/line.png')",
        infographics: "url('/images/infographics.svg')",
      },
      boxShadow: {
        "custom-primary": "4px 4px 25px 0 rgba(90, 103, 216, 0.2)",
      },
    },
  },
  plugins: [],
};
